#!/usr/bin/env bash
# =============================================================================
#  boot_agent-harness-skills.sh
#  Auto-generated by /harness:boot — do not edit manually.
#  Worktree : agent-harness-skills
#  Generated: 2026-03-22T00:00:00Z
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------
export PORT=8601
export HARNESS_WORKTREE_ID="agent-harness-skills"

# ---------------------------------------------------------------------------
# Resolve working directory
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ---------------------------------------------------------------------------
# Log file
# ---------------------------------------------------------------------------
LOG_FILE="${HARNESS_LOG_FILE:-/tmp/harness_agent-harness-skills.log}"

echo "[harness:boot] Starting application..."
echo "[harness:boot] Worktree : agent-harness-skills"
echo "[harness:boot] Port     : $PORT"
echo "[harness:boot] Log file : $LOG_FILE"
echo "[harness:boot] Command  : python -m http.server \$PORT"

# ---------------------------------------------------------------------------
# Launch application
# ---------------------------------------------------------------------------
python -m http.server "$PORT" \
    >> "$LOG_FILE" 2>&1 &

APP_PID=$!
echo "[harness:boot] Application started (PID: $APP_PID)"

# ---------------------------------------------------------------------------
# Health check — poll until ready or timeout
# ---------------------------------------------------------------------------
HEALTH_URL="http://localhost:${PORT}/health"
HEALTH_TIMEOUT=30
HEALTH_INTERVAL=1
ELAPSED=0

echo "[harness:boot] Polling health check: $HEALTH_URL (timeout: ${HEALTH_TIMEOUT}s)"

until curl -sf -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null | grep -qE '^(2[0-9]{2})$'; do
    if ! kill -0 "$APP_PID" 2>/dev/null; then
        echo "[harness:boot] ✗ Application process died (PID $APP_PID)" >&2
        echo "[harness:boot]   Check logs: $LOG_FILE" >&2
        exit 1
    fi
    if [ "$ELAPSED" -ge "$HEALTH_TIMEOUT" ]; then
        echo "[harness:boot] ✗ Health check timed out after ${ELAPSED}s" >&2
        echo "[harness:boot]   Check logs: $LOG_FILE" >&2
        kill "$APP_PID" 2>/dev/null || true
        exit 1
    fi
    sleep "$HEALTH_INTERVAL"
    ELAPSED=$((ELAPSED + HEALTH_INTERVAL))
done

echo "[harness:boot] ✓ Instance ready"
echo "[harness:boot]   PID:        $APP_PID"
echo "[harness:boot]   Port:       $PORT"
echo "[harness:boot]   Health URL: $HEALTH_URL"
echo "[harness:boot]   Elapsed:    ${ELAPSED}s"

# ---------------------------------------------------------------------------
# Register with state service (best-effort, non-fatal)
# ---------------------------------------------------------------------------
FEATURE_ID="${HARNESS_FEATURE_ID:-}"
STATE_URL="${CLAW_FORGE_STATE_URL:-http://localhost:8888}"
SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"

if [ -n "$FEATURE_ID" ]; then
    curl -sf -X PATCH "$STATE_URL/features/$FEATURE_ID" \
        -H "Content-Type: application/json" \
        -d "{
              \"boot_port\": $PORT,
              \"boot_pid\": $APP_PID,
              \"boot_health_url\": \"$HEALTH_URL\",
              \"boot_script\": \"$SCRIPT_PATH\"
            }" \
    && echo "[harness:boot] Registered instance with state service ($STATE_URL)" \
    || echo "[harness:boot] Warning: state service update failed (non-fatal)"
fi

# Export for downstream use
export APP_PID
export HEALTH_URL
