"""
skills/perf_hooks.py — Agent Performance Measurement Hooks

Provides lightweight hooks so agents can instrument and query three key metrics:

  * Response time  — wall-clock elapsed time for any labelled operation (ms)
  * Memory RSS     — resident-set-size of the current process at a point in time (MB)
  * Startup        — agent initialisation duration (ms)

All measurements are appended to ``docs/exec-plans/perf.md`` as an append-only
Markdown table so every agent in a plan shares one persistent audit trail.
Active timer state (start timestamps) is held in
``docs/exec-plans/perf-timers.json`` so a ``start`` call in one shell and a
matching ``stop`` call in a later shell both resolve correctly.

Usage (CLI)
-----------
  # Start a response-time timer
  python skills/perf_hooks.py start \\
      --label "call_llm" \\
      --agent "agent/coder-v1"

  # Stop the timer and record elapsed ms
  python skills/perf_hooks.py stop \\
      --label "call_llm" \\
      --agent "agent/coder-v1"

  # Sample current process memory (RSS in MB)
  python skills/perf_hooks.py sample-memory \\
      --label "after_load_index" \\
      --agent "agent/coder-v1"

  # Record a known startup duration (e.g. measured externally)
  python skills/perf_hooks.py record-startup \\
      --agent "agent/coder-v1" \\
      --duration-ms 1240.5

  # List all measurements (or filter by agent / metric)
  python skills/perf_hooks.py list
  python skills/perf_hooks.py list --agent "agent/coder-v1"
  python skills/perf_hooks.py list --metric response_time

  # Print aggregate stats (min / max / mean / p95 / count) per metric+label
  python skills/perf_hooks.py stats
  python skills/perf_hooks.py stats --agent "agent/coder-v1"
  python skills/perf_hooks.py stats --metric startup

Programmatic use
----------------
  from skills.perf_hooks import PerfHooks

  hooks = PerfHooks()

  # --- Context manager (recommended for response time) ---
  with hooks.timer("call_llm", agent="agent/coder-v1") as t:
      response = my_llm_call()
  print(f"Elapsed: {t.elapsed_ms:.1f} ms")

  # --- Manual start / stop ---
  hooks.start_timer("build_index", agent="agent/coder-v1")
  build_the_index()
  elapsed_ms = hooks.stop_timer("build_index", agent="agent/coder-v1")

  # --- Memory snapshot ---
  mb = hooks.sample_memory("after_embed", agent="agent/coder-v1")

  # --- Startup shorthand ---
  hooks.record_startup(agent="agent/coder-v1", duration_ms=980.0)

  # --- Query ---
  measurements = hooks.list(metric="response_time")
  hooks.stats()

Metric kinds
------------
  response_time  — elapsed wall-clock time for a labelled span (unit: ms)
  memory_rss     — resident-set-size of the measuring process  (unit: MB)
  startup        — agent initialisation / cold-start duration  (unit: ms)
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Generator, Iterator, Optional

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parent.parent
PERF_FILE   = _REPO_ROOT / "docs" / "exec-plans" / "perf.md"
TIMER_STATE = _REPO_ROOT / "docs" / "exec-plans" / "perf-timers.json"

# ---------------------------------------------------------------------------
# Metric / unit constants
# ---------------------------------------------------------------------------
METRIC_RESPONSE_TIME = "response_time"
METRIC_MEMORY_RSS    = "memory_rss"
METRIC_STARTUP       = "startup"

VALID_METRICS = [METRIC_RESPONSE_TIME, METRIC_MEMORY_RSS, METRIC_STARTUP]

METRIC_UNIT: dict[str, str] = {
    METRIC_RESPONSE_TIME: "ms",
    METRIC_MEMORY_RSS:    "MB",
    METRIC_STARTUP:       "ms",
}

METRIC_LABEL: dict[str, str] = {
    METRIC_RESPONSE_TIME: "⏱  response_time",
    METRIC_MEMORY_RSS:    "🧠 memory_rss",
    METRIC_STARTUP:       "🚀 startup",
}

# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------
_HEADER = """\
# Agent Performance Measurements

> Auto-generated by `skills/perf_hooks.py` — do not edit manually.
> Agents append entries when timing operations, sampling memory, or recording startup.

<!-- perf_hooks append new rows here — do not remove this comment -->

| Timestamp (UTC) | Agent | Metric | Label | Value | Unit | Notes |
|-----------------|-------|--------|-------|-------|------|-------|
"""

_ANCHOR = "<!-- perf_hooks append new rows here — do not remove this comment -->"
_TABLE_HEADER_PREFIX = "| Timestamp (UTC) |"


def _escape(value: str) -> str:
    """Escape pipe characters so they don't break Markdown tables."""
    return str(value).replace("|", "\\|")


def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ensure_perf_file() -> None:
    PERF_FILE.parent.mkdir(parents=True, exist_ok=True)
    if not PERF_FILE.exists():
        PERF_FILE.write_text(_HEADER, encoding="utf-8")


def _build_row(
    timestamp: str,
    agent: str,
    metric: str,
    label: str,
    value: float,
    unit: str,
    notes: str,
) -> str:
    cols = [timestamp, agent, METRIC_LABEL[metric], label, f"{value:.3f}", unit, notes or "—"]
    return "| " + " | ".join(_escape(c) for c in cols) + " |"


# ---------------------------------------------------------------------------
# Measurement dataclass
# ---------------------------------------------------------------------------
class Measurement:
    """Parsed representation of a single performance measurement row."""

    __slots__ = ("timestamp", "agent", "metric", "label", "value", "unit", "notes")

    def __init__(
        self,
        timestamp: str,
        agent: str,
        metric: str,
        label: str,
        value: float,
        unit: str,
        notes: str,
    ) -> None:
        self.timestamp = timestamp
        self.agent     = agent
        self.metric    = metric
        self.label     = label
        self.value     = value
        self.unit      = unit
        self.notes     = notes

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"Measurement(timestamp={self.timestamp!r}, agent={self.agent!r}, "
            f"metric={self.metric!r}, label={self.label!r}, value={self.value}, "
            f"unit={self.unit!r}, notes={self.notes!r})"
        )

    def as_dict(self) -> dict:
        return {s: getattr(self, s) for s in self.__slots__}


def _parse_row(line: str) -> Optional[Measurement]:
    """Parse a Markdown table data row into a Measurement, or return None."""
    line = line.strip()
    if not line.startswith("|") or line.startswith("|---") or line.startswith(_TABLE_HEADER_PREFIX):
        return None
    parts = [p.strip() for p in line.strip("|").split("|")]
    if len(parts) < 6:
        return None
    timestamp, agent, metric_label, label, value_str, unit, *rest = parts
    notes = rest[0] if rest else ""

    # Reverse-map display label → canonical metric key
    metric = "unknown"
    for key, display in METRIC_LABEL.items():
        if key in metric_label or display in metric_label:
            metric = key
            break

    def _unescape(v: str) -> str:
        return v.replace("\\|", "|")

    try:
        value = float(value_str)
    except ValueError:
        value = 0.0

    return Measurement(
        timestamp=_unescape(timestamp),
        agent=_unescape(agent),
        metric=metric,
        label=_unescape(label),
        value=value,
        unit=_unescape(unit),
        notes=_unescape(notes) if notes != "—" else "",
    )


# ---------------------------------------------------------------------------
# Timer state (persisted as JSON so start/stop can span processes)
# ---------------------------------------------------------------------------
_TimerKey = str  # "{agent}:{label}"


def _timer_key(agent: str, label: str) -> _TimerKey:
    return f"{agent}:{label}"


def _load_timers() -> dict[_TimerKey, float]:
    if not TIMER_STATE.exists():
        return {}
    try:
        return json.loads(TIMER_STATE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _save_timers(state: dict[_TimerKey, float]) -> None:
    TIMER_STATE.parent.mkdir(parents=True, exist_ok=True)
    tmp = TIMER_STATE.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(state, indent=2), encoding="utf-8")
    tmp.replace(TIMER_STATE)  # atomic rename on POSIX


# ---------------------------------------------------------------------------
# Memory sampling (no third-party dependencies)
# ---------------------------------------------------------------------------
def _rss_mb() -> float:
    """Return the current process RSS in megabytes.

    Tries (in order):
    1. ``/proc/self/status`` (Linux)
    2. ``resource.getrusage`` (macOS / BSD — ru_maxrss is bytes on macOS,
       kilobytes on Linux, so we handle both via /proc first)
    3. Returns 0.0 if neither is available.
    """
    # Linux: /proc/self/status gives VmRSS in kB
    proc_status = Path("/proc/self/status")
    if proc_status.exists():
        try:
            for raw_line in proc_status.read_text(encoding="utf-8").splitlines():
                if raw_line.startswith("VmRSS:"):
                    kb = int(raw_line.split()[1])
                    return round(kb / 1024.0, 3)
        except (OSError, ValueError, IndexError):
            pass

    # macOS / BSD: resource.getrusage — ru_maxrss is bytes on macOS
    try:
        import resource  # noqa: PLC0415
        rusage = resource.getrusage(resource.RUSAGE_SELF)
        rss_raw = rusage.ru_maxrss
        # Darwin returns bytes; other POSIX returns kilobytes
        if sys.platform == "darwin":
            return round(rss_raw / (1024.0 * 1024.0), 3)
        return round(rss_raw / 1024.0, 3)
    except (ImportError, AttributeError):
        pass

    return 0.0


# ---------------------------------------------------------------------------
# Context manager helper
# ---------------------------------------------------------------------------
class _TimerContext:
    """Returned by :py:meth:`PerfHooks.timer`; exposes ``elapsed_ms`` after exit."""

    def __init__(self) -> None:
        self.elapsed_ms: float = 0.0
        self._start: float = 0.0

    def _begin(self) -> None:
        self._start = time.perf_counter()

    def _end(self) -> float:
        self.elapsed_ms = (time.perf_counter() - self._start) * 1000.0
        return self.elapsed_ms


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
class PerfHooks:
    """Performance measurement hooks — response times, memory, and startup.

    All ``record_*`` methods append to ``docs/exec-plans/perf.md``.
    ``start_timer`` / ``stop_timer`` persist state in
    ``docs/exec-plans/perf-timers.json`` so they survive process boundaries.
    """

    def __init__(
        self,
        perf_file: Optional[Path] = None,
        timer_state: Optional[Path] = None,
    ) -> None:
        self._file   = Path(perf_file)   if perf_file   else PERF_FILE
        self._timers = Path(timer_state) if timer_state else TIMER_STATE

    # ------------------------------------------------------------------
    # Internal write helper
    # ------------------------------------------------------------------

    def _record(
        self,
        metric: str,
        label: str,
        value: float,
        agent: str,
        notes: str = "",
        timestamp: Optional[str] = None,
    ) -> Measurement:
        if metric not in VALID_METRICS:
            raise ValueError(
                f"Unknown metric {metric!r}. Valid: {', '.join(VALID_METRICS)}"
            )
        ts   = timestamp or _now_utc()
        unit = METRIC_UNIT[metric]
        _ensure_perf_file()
        row = _build_row(ts, agent, metric, label, value, unit, notes)
        with self._file.open("a", encoding="utf-8") as fh:
            fh.write(row + "\n")
        print(
            f"[perf_hooks] ✔ recorded {metric} label={label!r} "
            f"value={value:.3f}{unit} agent={agent!r}",
            file=sys.stderr,
        )
        return Measurement(
            timestamp=ts,
            agent=agent,
            metric=metric,
            label=label,
            value=value,
            unit=unit,
            notes=notes,
        )

    # ------------------------------------------------------------------
    # Response time
    # ------------------------------------------------------------------

    def start_timer(self, label: str, agent: str) -> float:
        """Record the start of a timed span.

        Persists the start epoch to ``perf-timers.json`` so the matching
        :py:meth:`stop_timer` call can be made from a different process.

        Parameters
        ----------
        label:
            Unique name for this operation (e.g. ``"call_llm"``).
        agent:
            Agent identifier.

        Returns
        -------
        float
            The ``time.time()`` epoch at which the timer was started.
        """
        state = _load_timers()
        key = _timer_key(agent, label)
        t = time.time()
        state[key] = t
        _save_timers(state)
        print(
            f"[perf_hooks] ▶ timer started label={label!r} agent={agent!r}",
            file=sys.stderr,
        )
        return t

    def stop_timer(
        self,
        label: str,
        agent: str,
        notes: str = "",
        timestamp: Optional[str] = None,
    ) -> float:
        """Stop a previously started timer and record the elapsed duration.

        Parameters
        ----------
        label:
            Must match the label passed to :py:meth:`start_timer`.
        agent:
            Agent identifier.
        notes:
            Optional free-text annotation (e.g. ``"cache hit"``).
        timestamp:
            Override the recorded UTC timestamp; defaults to now.

        Returns
        -------
        float
            Elapsed time in milliseconds.

        Raises
        ------
        KeyError
            If no matching ``start_timer`` entry is found.
        """
        state = _load_timers()
        key = _timer_key(agent, label)
        if key not in state:
            raise KeyError(
                f"No active timer for label={label!r} agent={agent!r}. "
                "Did you call start_timer() first?"
            )
        elapsed_ms = (time.time() - state.pop(key)) * 1000.0
        _save_timers(state)
        self._record(
            METRIC_RESPONSE_TIME, label, elapsed_ms, agent, notes, timestamp
        )
        return elapsed_ms

    @contextmanager
    def timer(
        self, label: str, agent: str, notes: str = ""
    ) -> Generator[_TimerContext, None, None]:
        """Context manager that measures and records response time.

        Example
        -------
        ::

            with hooks.timer("embed_docs", agent="agent/coder-v1") as t:
                embeddings = embed(docs)
            print(f"Embedding took {t.elapsed_ms:.1f} ms")

        Parameters
        ----------
        label:
            Name for this operation.
        agent:
            Agent identifier.
        notes:
            Optional annotation written to the measurements log.

        Yields
        ------
        _TimerContext
            Object whose ``elapsed_ms`` attribute is populated on ``__exit__``.
        """
        ctx = _TimerContext()
        ctx._begin()
        try:
            yield ctx
        finally:
            ctx._end()
            self._record(
                METRIC_RESPONSE_TIME, label, ctx.elapsed_ms, agent, notes
            )

    # ------------------------------------------------------------------
    # Memory
    # ------------------------------------------------------------------

    def sample_memory(
        self,
        label: str,
        agent: str,
        notes: str = "",
        timestamp: Optional[str] = None,
    ) -> float:
        """Sample and record the current process RSS.

        Parameters
        ----------
        label:
            Descriptive name for the measurement point
            (e.g. ``"after_load_index"``).
        agent:
            Agent identifier.
        notes:
            Optional free-text annotation.
        timestamp:
            Override the recorded UTC timestamp; defaults to now.

        Returns
        -------
        float
            Resident-set-size in megabytes.
        """
        mb = _rss_mb()
        self._record(METRIC_MEMORY_RSS, label, mb, agent, notes, timestamp)
        return mb

    # ------------------------------------------------------------------
    # Startup
    # ------------------------------------------------------------------

    def record_startup(
        self,
        agent: str,
        duration_ms: float,
        notes: str = "",
        timestamp: Optional[str] = None,
    ) -> Measurement:
        """Record agent initialisation / cold-start duration.

        Parameters
        ----------
        agent:
            Agent identifier.
        duration_ms:
            Startup duration in milliseconds (measure with
            ``time.perf_counter()`` before and after your init code).
        notes:
            Optional free-text annotation.
        timestamp:
            Override the recorded UTC timestamp; defaults to now.

        Returns
        -------
        Measurement
            The entry that was written.
        """
        return self._record(
            METRIC_STARTUP, "startup", duration_ms, agent, notes, timestamp
        )

    # ------------------------------------------------------------------
    # Read / Query
    # ------------------------------------------------------------------

    def list(
        self,
        agent: Optional[str] = None,
        metric: Optional[str] = None,
        label: Optional[str] = None,
    ) -> list[Measurement]:
        """Return recorded measurements, optionally filtered.

        Parameters
        ----------
        agent:
            Filter to a specific agent identifier.
        metric:
            Filter to ``response_time``, ``memory_rss``, or ``startup``.
        label:
            Filter to a specific operation label.

        Returns
        -------
        list[Measurement]
            Entries in file order (oldest first).
        """
        if not self._file.exists():
            return []
        results: list[Measurement] = []
        for raw_line in self._file.read_text(encoding="utf-8").splitlines():
            m = _parse_row(raw_line)
            if m is None:
                continue
            if agent  and m.agent  != agent:
                continue
            if metric and m.metric != metric:
                continue
            if label  and m.label  != label:
                continue
            results.append(m)
        return results

    def stats(
        self,
        agent: Optional[str] = None,
        metric: Optional[str] = None,
    ) -> None:
        """Print aggregate statistics (min / max / mean / p95 / count) to stdout.

        Groups results by ``(metric, label)`` pair.

        Parameters
        ----------
        agent:
            Restrict to a specific agent.
        metric:
            Restrict to one metric kind.
        """
        measurements = self.list(agent=agent, metric=metric)
        if not measurements:
            print("(no measurements found)")
            return

        # Group values by (metric, label)
        groups: dict[tuple[str, str], list[float]] = {}
        for m in measurements:
            key = (m.metric, m.label)
            groups.setdefault(key, []).append(m.value)

        header = (
            f"{'Metric':<16} {'Label':<28} {'N':>5}  "
            f"{'Min':>10}  {'Max':>10}  {'Mean':>10}  {'p95':>10}  {'Unit':<5}"
        )
        print(header)
        print("-" * len(header))
        for (met, lbl) in sorted(groups):
            vals = sorted(groups[(met, lbl)])
            n    = len(vals)
            vmin = vals[0]
            vmax = vals[-1]
            mean = sum(vals) / n
            # p95: nearest-rank method
            p95_idx = max(0, math.ceil(0.95 * n) - 1)
            p95     = vals[p95_idx]
            unit    = METRIC_UNIT.get(met, "")
            print(
                f"{met:<16} {lbl:<28} {n:>5}  "
                f"{vmin:>10.3f}  {vmax:>10.3f}  {mean:>10.3f}  {p95:>10.3f}  {unit:<5}"
            )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="perf_hooks.py",
        description="Record and query agent performance measurements.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # --- start ---
    sp = sub.add_parser("start", help="Start a response-time timer.")
    sp.add_argument("--label",  required=True, help="Operation label (e.g. 'call_llm').")
    sp.add_argument("--agent",  required=True, help="Agent identifier.")

    # --- stop ---
    ep = sub.add_parser("stop", help="Stop a timer and record elapsed ms.")
    ep.add_argument("--label",   required=True, help="Operation label (must match start).")
    ep.add_argument("--agent",   required=True, help="Agent identifier.")
    ep.add_argument("--notes",   default="",    help="Optional annotation.")
    ep.add_argument("--timestamp", default=None, help="Override UTC timestamp (ISO-8601).")

    # --- sample-memory ---
    mp = sub.add_parser("sample-memory", help="Sample and record current process RSS.")
    mp.add_argument("--label",   required=True, help="Measurement point label.")
    mp.add_argument("--agent",   required=True, help="Agent identifier.")
    mp.add_argument("--notes",   default="",    help="Optional annotation.")
    mp.add_argument("--timestamp", default=None, help="Override UTC timestamp (ISO-8601).")

    # --- record-startup ---
    rp = sub.add_parser("record-startup", help="Record agent startup duration.")
    rp.add_argument("--agent",       required=True, type=str,   help="Agent identifier.")
    rp.add_argument("--duration-ms", required=True, type=float, help="Startup duration in ms.")
    rp.add_argument("--notes",       default="",                help="Optional annotation.")
    rp.add_argument("--timestamp",   default=None,              help="Override UTC timestamp.")

    # --- list ---
    lp = sub.add_parser("list", help="Print measurement rows.")
    lp.add_argument("--agent",  default=None, help="Filter to agent identifier.")
    lp.add_argument("--metric", default=None, choices=VALID_METRICS, help="Filter to metric kind.")
    lp.add_argument("--label",  default=None, help="Filter to operation label.")

    # --- stats ---
    tp = sub.add_parser("stats", help="Print aggregate stats per metric+label.")
    tp.add_argument("--agent",  default=None, help="Restrict to agent identifier.")
    tp.add_argument("--metric", default=None, choices=VALID_METRICS, help="Restrict to metric kind.")

    return parser


def main(argv: Optional[list[str]] = None) -> None:
    parser = _build_parser()
    args   = parser.parse_args(argv)
    hooks  = PerfHooks()

    if args.command == "start":
        t = hooks.start_timer(label=args.label, agent=args.agent)
        print(f"Timer started: label={args.label!r} agent={args.agent!r} epoch={t:.6f}")

    elif args.command == "stop":
        try:
            elapsed = hooks.stop_timer(
                label=args.label,
                agent=args.agent,
                notes=args.notes,
                timestamp=args.timestamp,
            )
        except KeyError as exc:
            print(f"[perf_hooks] ERROR: {exc}", file=sys.stderr)
            sys.exit(1)
        print(f"Elapsed: {elapsed:.3f} ms  label={args.label!r} agent={args.agent!r}")

    elif args.command == "sample-memory":
        mb = hooks.sample_memory(
            label=args.label,
            agent=args.agent,
            notes=args.notes,
            timestamp=args.timestamp,
        )
        print(f"RSS: {mb:.3f} MB  label={args.label!r} agent={args.agent!r}")

    elif args.command == "record-startup":
        m = hooks.record_startup(
            agent=args.agent,
            duration_ms=args.duration_ms,
            notes=args.notes,
            timestamp=args.timestamp,
        )
        print(
            f"Startup recorded: {m.value:.3f} ms  agent={m.agent!r}"
            + (f"  notes={m.notes!r}" if m.notes else "")
        )

    elif args.command == "list":
        entries = hooks.list(agent=args.agent, metric=args.metric, label=args.label)
        if not entries:
            print("(no measurements found)")
            return
        col_ts  = 22
        col_ag  = 22
        col_met = 16
        col_lbl = 28
        col_val = 12
        col_u   = 5
        hdr = (
            f"{'Timestamp':<{col_ts}} {'Agent':<{col_ag}} "
            f"{'Metric':<{col_met}} {'Label':<{col_lbl}} "
            f"{'Value':>{col_val}} {'Unit':<{col_u}}  Notes"
        )
        print(hdr)
        print("-" * (len(hdr) + 10))
        for e in entries:
            print(
                f"{e.timestamp:<{col_ts}} {e.agent:<{col_ag}} "
                f"{e.metric:<{col_met}} {e.label:<{col_lbl}} "
                f"{e.value:>{col_val}.3f} {e.unit:<{col_u}}  {e.notes}"
            )

    elif args.command == "stats":
        hooks.stats(agent=args.agent, metric=args.metric)


if __name__ == "__main__":
    main()
