"""
skills/progress_log.py — Agent Progress Log

Agents use this script to append timestamped entries as they complete (or
start / fail / skip) steps within a plan.  All entries are written to
docs/exec-plans/progress.md as an append-only Markdown table.

Usage (CLI)
-----------
  # Record that a step started
  python skills/progress_log.py append \
      --plan-id "feature/auth-refactor" \
      --step "1. Scaffold AuthService" \
      --status started \
      --agent "agent/coder-v1"

  # Record successful completion
  python skills/progress_log.py append \
      --plan-id "feature/auth-refactor" \
      --step "1. Scaffold AuthService" \
      --status done \
      --message "Created src/auth/service.py; all tests green" \
      --agent "agent/coder-v1"

  # Record a failure with detail
  python skills/progress_log.py append \
      --plan-id "feature/auth-refactor" \
      --step "2. Wire middleware" \
      --status failed \
      --message "Import cycle detected; needs arch review" \
      --agent "agent/coder-v1"

  # Show recent entries (all plans)
  python skills/progress_log.py list

  # Show entries for one plan only
  python skills/progress_log.py list --plan-id "feature/auth-refactor"

  # Print a per-plan summary (done / total)
  python skills/progress_log.py summary

Programmatic use
----------------
  from skills.progress_log import ProgressLog

  log = ProgressLog()

  # Append an entry
  log.append(
      plan_id="feature/auth-refactor",
      step="1. Scaffold AuthService",
      status="done",
      agent="agent/coder-v1",
      message="Created src/auth/service.py; all tests green",
  )

  # List entries for a specific plan
  entries = log.list(plan_id="feature/auth-refactor")
  for e in entries:
      print(e)

  # Print a summary table to stdout
  log.summary()

Entry statuses
--------------
  started   — agent has begun work on the step
  done      — step completed successfully
  failed    — step could not be completed; see message for detail
  skipped   — step intentionally bypassed (e.g. not applicable)
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parent.parent
PROGRESS_FILE = _REPO_ROOT / "docs" / "exec-plans" / "progress.md"

# ---------------------------------------------------------------------------
# Status helpers
# ---------------------------------------------------------------------------
STATUS_EMOJI: dict[str, str] = {
    "started": "🔵 started",
    "done":    "✅ done",
    "failed":  "❌ failed",
    "skipped": "⏭️  skipped",
}

VALID_STATUSES = list(STATUS_EMOJI)


def _normalise_status(raw: str) -> str:
    s = raw.strip().lower()
    if s not in STATUS_EMOJI:
        raise ValueError(
            f"Unknown status {raw!r}. Valid values: {', '.join(VALID_STATUSES)}"
        )
    return s


# ---------------------------------------------------------------------------
# Markdown file helpers
# ---------------------------------------------------------------------------
_HEADER = """\
# Agent Progress Log

> Auto-generated by `skills/progress_log.py` — do not edit manually.
> Agents append entries as they start, complete, fail, or skip plan steps.

<!-- agents append new rows here — do not remove this comment -->

| Timestamp (UTC) | Plan ID | Step | Status | Agent | Message |
|-----------------|---------|------|--------|-------|---------|
"""

_ANCHOR = "<!-- agents append new rows here — do not remove this comment -->"

_TABLE_HEADER = (
    "| Timestamp (UTC) | Plan ID | Step | Status | Agent | Message |\n"
    "|-----------------|---------|------|--------|-------|---------|"
)


def _escape(value: str) -> str:
    """Escape pipe characters so they don't break Markdown tables."""
    return value.replace("|", "\\|")


def _now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ensure_file() -> None:
    """Create docs/exec-plans/progress.md if it does not yet exist."""
    PROGRESS_FILE.parent.mkdir(parents=True, exist_ok=True)
    if not PROGRESS_FILE.exists():
        PROGRESS_FILE.write_text(_HEADER, encoding="utf-8")


def _build_row(
    timestamp: str,
    plan_id: str,
    step: str,
    status: str,
    agent: str,
    message: str,
) -> str:
    label = STATUS_EMOJI[status]
    cols = [timestamp, plan_id, step, label, agent, message or "—"]
    return "| " + " | ".join(_escape(c) for c in cols) + " |"


# ---------------------------------------------------------------------------
# Entry dataclass (simple namedtuple-style dict for portability)
# ---------------------------------------------------------------------------
class ProgressEntry:
    """Parsed representation of a single progress log row."""

    __slots__ = ("timestamp", "plan_id", "step", "status", "agent", "message")

    def __init__(
        self,
        timestamp: str,
        plan_id: str,
        step: str,
        status: str,
        agent: str,
        message: str,
    ) -> None:
        self.timestamp = timestamp
        self.plan_id = plan_id
        self.step = step
        self.status = status
        self.agent = agent
        self.message = message

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"ProgressEntry(timestamp={self.timestamp!r}, plan_id={self.plan_id!r}, "
            f"step={self.step!r}, status={self.status!r}, agent={self.agent!r}, "
            f"message={self.message!r})"
        )

    def as_dict(self) -> dict[str, str]:
        return {s: getattr(self, s) for s in self.__slots__}


def _parse_row(line: str) -> Optional[ProgressEntry]:
    """Parse a Markdown table row into a ProgressEntry, or return None."""
    line = line.strip()
    if not line.startswith("|") or line.startswith("|---") or line.startswith("| Tim"):
        return None
    # Strip leading/trailing pipe, split on |
    parts = [p.strip() for p in line.strip("|").split("|")]
    if len(parts) < 6:
        return None
    timestamp, plan_id, step, status_label, agent, *rest = parts
    message = rest[0] if rest else ""
    # Reverse-map status label → canonical status key
    status = "unknown"
    for key, label in STATUS_EMOJI.items():
        if key in status_label.lower() or label in status_label:
            status = key
            break
    # Un-escape pipes
    def _unescape(v: str) -> str:
        return v.replace("\\|", "|")

    return ProgressEntry(
        timestamp=_unescape(timestamp),
        plan_id=_unescape(plan_id),
        step=_unescape(step),
        status=status,
        agent=_unescape(agent),
        message=_unescape(message) if message != "—" else "",
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
class ProgressLog:
    """Append-only progress log stored as a Markdown table.

    All mutating methods are safe to call from multiple agents provided the
    OS serialises ``open(..., 'a')`` appends (true on POSIX and Windows for
    local filesystems).
    """

    def __init__(self, log_file: Optional[Path] = None) -> None:
        self._file = Path(log_file) if log_file else PROGRESS_FILE

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def append(
        self,
        plan_id: str,
        step: str,
        status: str,
        agent: str,
        message: str = "",
        timestamp: Optional[str] = None,
    ) -> ProgressEntry:
        """Append a timestamped progress entry.

        Parameters
        ----------
        plan_id:
            Identifier for the plan / feature (e.g. ``"feature/auth-refactor"``).
        step:
            Human-readable step label (e.g. ``"3. Write unit tests"``).
        status:
            One of ``started``, ``done``, ``failed``, ``skipped``.
        agent:
            Identifier of the agent recording the entry
            (e.g. ``"agent/coder-v1"``).
        message:
            Optional free-text detail (test counts, error excerpts, …).
        timestamp:
            ISO-8601 UTC string; defaults to *now*.

        Returns
        -------
        ProgressEntry
            The entry that was written.
        """
        status = _normalise_status(status)
        ts = timestamp or _now_utc()
        _ensure_file()

        row = _build_row(ts, plan_id, step, status, agent, message)

        # Atomic-ish append — on POSIX, O_APPEND writes are atomic up to PIPE_BUF.
        with self._file.open("a", encoding="utf-8") as fh:
            fh.write(row + "\n")

        print(f"[progress_log] ✔ appended {status!r} entry for step {step!r}", file=sys.stderr)
        return ProgressEntry(
            timestamp=ts,
            plan_id=plan_id,
            step=step,
            status=status,
            agent=agent,
            message=message,
        )

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    def list(self, plan_id: Optional[str] = None) -> list[ProgressEntry]:
        """Return all log entries, optionally filtered to *plan_id*.

        Parameters
        ----------
        plan_id:
            When supplied, only entries whose ``plan_id`` matches are returned.

        Returns
        -------
        list[ProgressEntry]
            Entries in file order (oldest first).
        """
        if not self._file.exists():
            return []

        entries: list[ProgressEntry] = []
        for line in self._file.read_text(encoding="utf-8").splitlines():
            entry = _parse_row(line)
            if entry is None:
                continue
            if plan_id and entry.plan_id != plan_id:
                continue
            entries.append(entry)
        return entries

    def summary(self, plan_id: Optional[str] = None) -> None:
        """Print a per-plan progress summary to *stdout*.

        For each plan shows how many steps are ``done``, ``failed``,
        ``skipped``, and still ``started`` (in-progress / not yet resolved).

        Parameters
        ----------
        plan_id:
            When supplied, restricts the summary to that plan only.
        """
        entries = self.list(plan_id=plan_id)
        if not entries:
            print("(no progress entries found)")
            return

        # Track the *latest* status per (plan_id, step) pair.
        latest: dict[tuple[str, str], str] = {}
        for e in entries:
            latest[(e.plan_id, e.step)] = e.status

        # Aggregate by plan.
        plan_counts: dict[str, dict[str, int]] = defaultdict(
            lambda: {"done": 0, "failed": 0, "skipped": 0, "started": 0, "total": 0}
        )
        for (pid, _step), status in latest.items():
            plan_counts[pid][status] += 1
            plan_counts[pid]["total"] += 1

        col_w = max(len(pid) for pid in plan_counts) + 2
        header = (
            f"{'Plan ID':<{col_w}} {'Total':>5}  {'✅ done':>8}  "
            f"{'❌ failed':>9}  {'⏭️  skipped':>11}  {'🔵 started':>10}"
        )
        print(header)
        print("-" * len(header))
        for pid in sorted(plan_counts):
            c = plan_counts[pid]
            print(
                f"{pid:<{col_w}} {c['total']:>5}  {c['done']:>8}  "
                f"{c['failed']:>9}  {c['skipped']:>11}  {c['started']:>10}"
            )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="progress_log.py",
        description="Append and inspect agent progress log entries.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # --- append ---
    ap = sub.add_parser("append", help="Append a progress entry.")
    ap.add_argument(
        "--plan-id", required=True,
        help="Plan / feature identifier (e.g. 'feature/auth-refactor').",
    )
    ap.add_argument(
        "--step", required=True,
        help="Step label (e.g. '3. Write unit tests').",
    )
    ap.add_argument(
        "--status", required=True,
        choices=VALID_STATUSES,
        help="Completion status for this step.",
    )
    ap.add_argument(
        "--agent", required=True,
        help="Agent identifier (e.g. 'agent/coder-v1').",
    )
    ap.add_argument(
        "--message", default="",
        help="Optional free-text detail (error excerpt, test counts, …).",
    )
    ap.add_argument(
        "--timestamp", default=None,
        help="Override timestamp (ISO-8601 UTC). Defaults to now.",
    )

    # --- list ---
    lp = sub.add_parser("list", help="Print log entries as a table.")
    lp.add_argument(
        "--plan-id", default=None,
        help="Filter to a specific plan / feature.",
    )

    # --- summary ---
    sp = sub.add_parser("summary", help="Print per-plan progress summary.")
    sp.add_argument(
        "--plan-id", default=None,
        help="Restrict summary to one plan.",
    )

    return parser


def main(argv: Optional[list[str]] = None) -> None:
    parser = _build_parser()
    args = parser.parse_args(argv)
    log = ProgressLog()

    if args.command == "append":
        entry = log.append(
            plan_id=args.plan_id,
            step=args.step,
            status=args.status,
            agent=args.agent,
            message=args.message,
            timestamp=args.timestamp,
        )
        print(
            f"[{entry.timestamp}] {entry.plan_id} | {entry.step} | "
            f"{entry.status} | {entry.agent}"
            + (f" | {entry.message}" if entry.message else "")
        )

    elif args.command == "list":
        entries = log.list(plan_id=args.plan_id)
        if not entries:
            print("(no entries)")
            return
        header = (
            f"{'Timestamp':<22} {'Plan ID':<30} {'Step':<35} "
            f"{'Status':<10} {'Agent':<20} Message"
        )
        print(header)
        print("-" * len(header))
        for e in entries:
            print(
                f"{e.timestamp:<22} {e.plan_id:<30} {e.step:<35} "
                f"{e.status:<10} {e.agent:<20} {e.message}"
            )

    elif args.command == "summary":
        log.summary(plan_id=args.plan_id)


if __name__ == "__main__":
    main()
