import DeepDiveLayout from "../components/DeepDiveLayout";
import ScrollReveal from "../components/ScrollReveal";
import CodeBlock from "../components/CodeBlock";
import TerminalSim from "../components/TerminalSim";
import FeatureItem from "../components/FeatureItem";
import GlowBadge from "../components/GlowBadge";
import { features } from "../data/features";

const cliFeatures = features.filter((f) => f.category === "cli");

const tooManyCommands = `# Monday morning: what commands do I need again?

$ ruff check .                    # lint Python
$ mypy . --strict                 # type check
$ pytest tests/ -v                # run tests
$ pytest --cov=src --cov-report=term  # coverage
$ bandit -r src/                  # security scan
$ python -m pip_audit             # dependency audit
$ python scripts/check_arch.py    # architecture check
$ python scripts/check_principles.py  # principles check
$ python scripts/check_docs.py    # docs freshness
$ python scripts/gen_agents_md.py # regenerate AGENTS.md
$ python scripts/gen_eval.py      # regenerate EVALUATION.md

# 11 commands, different flags, different scripts.
# Nobody remembers them all. Half the team skips half of them.
# The CI config is 200 lines of YAML reproducing this list.`;

const configYaml = `# harness.config.yaml — generated by harness create
profile: standard          # starter | standard | advanced

gates:
  regression:
    enabled: true
    command: "pytest tests/ -v"
  coverage:
    enabled: true
    threshold: 90
  security:
    enabled: true
    tools: [bandit, pip-audit]
  architecture:
    enabled: true
  principles:
    enabled: true
    severity: critical     # fail on critical only
  docs-freshness:
    enabled: true
    max-age-days: 30
  type-safety:
    enabled: true
    command: "mypy . --strict"
  lint:
    enabled: true
    command: "ruff check ."

output:
  format: auto             # auto | json | yaml | table
  verbosity: normal        # quiet | normal | verbose | debug`;

const chainingExample = `# Before: run each command separately, check each result
$ harness create && harness lint && harness evaluate

# After: one invocation, pipeline execution
$ harness create --then lint --then evaluate

# Output format for CI consumption:
$ harness create --then lint --then evaluate --output-format json

# Progressive profiles for different team needs:
$ harness create --profile starter   # 5 artifacts, basics only
$ harness create --profile standard  # 14 artifacts, full suite
$ harness create --profile advanced  # 14 artifacts + custom gates`;

const pipelineLines = [
	{ text: "$ harness create --then lint --then evaluate", color: "text-white" },
	{ text: "", delay: 300 },
	{ text: "[1/3] harness create", color: "text-brand-cyan", delay: 400 },
	{ text: "  Scanning project... Python 3.12 + FastAPI detected", delay: 200 },
	{ text: "  \u2713 Generated 14 artifacts (harness_manifest.json written)", color: "text-brand-green", delay: 300 },
	{ text: "", delay: 200 },
	{ text: "[2/3] harness lint", color: "text-brand-cyan", delay: 400 },
	{ text: "  Running architectural checks...", delay: 200 },
	{ text: "  \u2713 architecture: 0 violations", color: "text-brand-green", delay: 200 },
	{ text: "  \u2713 principles: 0 critical (1 warning)", color: "text-brand-green", delay: 200 },
	{ text: "  \u2713 file-naming: all consistent", color: "text-brand-green", delay: 200 },
	{ text: "", delay: 200 },
	{ text: "[3/3] harness evaluate", color: "text-brand-cyan", delay: 400 },
	{ text: "  Running 8 evaluation gates...", delay: 200 },
	{ text: "  \u2713 regression: 247/247 passed", color: "text-brand-green", delay: 150 },
	{ text: "  \u2713 coverage: 92.4%", color: "text-brand-green", delay: 150 },
	{ text: "  \u2713 security: clean", color: "text-brand-green", delay: 150 },
	{ text: "  \u2713 architecture: passed", color: "text-brand-green", delay: 150 },
	{ text: "  \u2713 principles: passed", color: "text-brand-green", delay: 150 },
	{ text: "  \u2713 docs: fresh", color: "text-brand-green", delay: 150 },
	{ text: "  \u2713 types: passed", color: "text-brand-green", delay: 150 },
	{ text: "  \u2713 lint: passed", color: "text-brand-green", delay: 150 },
	{ text: "", delay: 200 },
	{ text: "Pipeline complete: 3/3 stages passed \u2713", color: "text-brand-green", delay: 400 },
	{ text: "Total time: 12.4s", color: "text-gray-500", delay: 200 },
];

interface Command {
	name: string;
	description: string;
}

const commands: Command[] = [
	{ name: "create", description: "Generate full harness from project scan" },
	{ name: "update", description: "Re-scan and update artifacts, preserving edits" },
	{ name: "lint", description: "Run all architectural and principle checks" },
	{ name: "evaluate", description: "Run all evaluation gates" },
	{ name: "boot", description: "Launch isolated app instance with health check" },
	{ name: "plan", description: "Create execution plan from description" },
	{ name: "status", description: "Show plans, gates, and harness health" },
	{ name: "resume", description: "Load plan state for context handoff" },
	{ name: "screenshot", description: "Capture application state as visual artifact" },
	{ name: "observe", description: "Tail structured logs by domain or trace_id" },
	{ name: "context", description: "Return minimal file paths and search patterns" },
	{ name: "search", description: "Search symbol index across the codebase" },
	{ name: "coordinate", description: "Cross-agent conflict detection and reordering" },
	{ name: "audit", description: "Per-artifact freshness scoring" },
	{ name: "handoff", description: "Generate context handoff for next agent" },
	{ name: "telemetry", description: "Report utilization and effectiveness scores" },
	{ name: "init", description: "Standalone shell script for non-CC environments" },
];

export default function CliPage() {
	return (
		<DeepDiveLayout categoryId="cli">
			{/* Act 1: The Problem */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Problem" color="purple" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						20 separate commands to remember
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Every project has its own collection of lint, test, check, and deploy commands
						with different flags and scripts. Nobody remembers them all, and half the
						team skips half of them.
					</p>
				</ScrollReveal>
				<ScrollReveal delay={0.2}>
					<CodeBlock code={tooManyCommands} lang="bash" filename="monday-morning.sh" />
				</ScrollReveal>
			</section>

			{/* Act 2: The Solution */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Solution" color="cyan" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						17 commands unified under one CLI with pipeline composition
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Harness provides a single CLI with consistent flags, structured output,
						progressive profiles, and <code className="text-brand-cyan">--then</code>{" "}
						chaining for single-invocation pipelines. One tool to remember, one config
						to maintain.
					</p>
				</ScrollReveal>

				<div className="grid gap-3 mb-8">
					{cliFeatures.map((f) => (
						<div key={f.id} id={f.id}>
							<FeatureItem feature={f} />
						</div>
					))}
				</div>

				<ScrollReveal delay={0.1}>
					<div className="space-y-6">
						<CodeBlock code={configYaml} lang="yaml" filename="harness.config.yaml" />
						<CodeBlock code={chainingExample} lang="bash" filename="--then chaining" />
					</div>
				</ScrollReveal>
			</section>

			{/* Act 3: See It In Action */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="See It In Action" color="green" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						Pipeline execution with --then chaining
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Watch a full create → lint → evaluate pipeline execute in a single invocation.
					</p>
				</ScrollReveal>

				<ScrollReveal delay={0.1}>
					<TerminalSim lines={pipelineLines} title="harness pipeline" />
				</ScrollReveal>

				{/* Command grid */}
				<ScrollReveal delay={0.2}>
					<h3 className="text-xl font-bold text-white mt-12 mb-6">All 17 commands</h3>
					<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
						{commands.map((cmd) => (
							<div
								key={cmd.name}
								className="glass rounded-lg p-4 hover:bg-white/5 transition-colors"
							>
								<code className="text-brand-cyan text-sm font-mono">
									harness {cmd.name}
								</code>
								<p className="text-xs text-gray-400 mt-1">{cmd.description}</p>
							</div>
						))}
					</div>
				</ScrollReveal>
			</section>
		</DeepDiveLayout>
	);
}
