import { useCallback, useRef, useState } from "react";
import DeepDiveLayout from "../components/DeepDiveLayout";
import ScrollReveal from "../components/ScrollReveal";
import CodeBlock from "../components/CodeBlock";
import FeatureItem from "../components/FeatureItem";
import GlowBadge from "../components/GlowBadge";
import { features } from "../data/features";

const gatesFeatures = features.filter((f) => f.category === "gates");

const shipAndPray = `$ git push origin main
$ kubectl rollout restart deployment/api

# 3 hours later...
[ALERT] 500 error rate spike: 12% of requests failing
[ALERT] Memory usage 94% — OOM kill imminent
[ALERT] Security: CVE-2024-1234 detected in production dependency

# Post-mortem:
# - Tests weren't run (CI was "too slow")
# - Coverage dropped from 91% to 67% in the last 3 PRs
# - Nobody noticed the vulnerable dependency update
# - Type errors were suppressed with "any" casts
# - Architecture violations let repo layer call UI directly`;

const evaluateMd = `# EVALUATION.md (generated by harness)

## Gate Configuration
All gates must pass before merge. Override via harness.config.yaml.

| Gate              | Threshold  | Severity | Auto-fix |
|-------------------|-----------|----------|----------|
| Regression Tests  | 100% pass | critical | no       |
| Coverage          | ≥ 90%     | critical | no       |
| Security Scan     | 0 high/critical | critical | no  |
| Architecture      | 0 violations | critical | no     |
| Principles        | 0 critical | warning  | partial  |
| Docs Freshness    | < 30 days  | warning  | yes     |
| Type Safety       | 0 errors   | critical | no      |
| Lint              | 0 warnings | warning  | yes     |`;

const evaluateOutput = `$ harness evaluate --format table

  Gate               Result     Detail
  ─────────────────  ─────────  ─────────────────────────
  Regression Tests   ✓ passed   247/247 tests passed
  Coverage           ✓ passed   92.4% (threshold: 90%)
  Security Scan      ✓ passed   0 vulnerabilities found
  Architecture       ✓ passed   0 boundary violations
  Principles         ✓ passed   0 critical, 1 warning
  Docs Freshness     ✓ passed   AGENTS.md: 2 days old
  Type Safety        ✓ passed   0 type errors
  Lint               ✓ passed   0 warnings on changed files

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Overall: 8/8 gates passed ✓  Ready to merge.`;

interface Gate {
	name: string;
	detail: string;
	pass: boolean;
}

const gates: Gate[] = [
	{ name: "Regression Tests", detail: "247/247 tests passed", pass: true },
	{ name: "Coverage", detail: "92.4% (threshold: 90%)", pass: true },
	{ name: "Security Scan", detail: "0 vulnerabilities found", pass: true },
	{ name: "Architecture", detail: "0 boundary violations", pass: true },
	{ name: "Principles", detail: "0 critical, 1 warning", pass: true },
	{ name: "Docs Freshness", detail: "AGENTS.md: 2 days old", pass: true },
	{ name: "Type Safety", detail: "0 type errors", pass: true },
	{ name: "Lint", detail: "0 warnings on changed files", pass: true },
];

export default function GatesPage() {
	const [visibleCount, setVisibleCount] = useState(0);
	const [running, setRunning] = useState(false);
	const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

	const runEvaluation = useCallback(() => {
		if (running) return;
		setVisibleCount(0);
		setRunning(true);
		let count = 0;
		timerRef.current = setInterval(() => {
			count += 1;
			setVisibleCount(count);
			if (count >= gates.length) {
				if (timerRef.current) clearInterval(timerRef.current);
				setRunning(false);
			}
		}, 400);
	}, [running]);

	const resetEvaluation = useCallback(() => {
		if (timerRef.current) clearInterval(timerRef.current);
		setRunning(false);
		setVisibleCount(0);
	}, []);

	return (
		<DeepDiveLayout categoryId="gates">
			{/* Act 1: The Problem */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Problem" color="purple" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						Ship and pray — no gates between code and production
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Without evaluation gates, broken code reaches production because nobody ran
						the tests, checked coverage, or audited dependencies. Each missing gate is
						a failure mode waiting to trigger at 2 AM.
					</p>
				</ScrollReveal>
				<ScrollReveal delay={0.2}>
					<CodeBlock code={shipAndPray} lang="bash" filename="incident-postmortem.log" />
				</ScrollReveal>
			</section>

			{/* Act 2: The Solution */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Solution" color="cyan" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						15 configurable gates that block bad code mechanically
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Harness generates an evaluation pipeline with regression tests, coverage
						thresholds, security scanning, architectural compliance, and more — all
						runnable in one command with structured output for CI integration.
					</p>
				</ScrollReveal>

				<div className="grid gap-3 mb-8">
					{gatesFeatures.map((f) => (
						<div key={f.id} id={f.id}>
							<FeatureItem feature={f} />
						</div>
					))}
				</div>

				<ScrollReveal delay={0.1}>
					<div className="space-y-6">
						<CodeBlock code={evaluateMd} lang="markdown" filename="EVALUATION.md (generated)" />
						<CodeBlock code={evaluateOutput} lang="bash" filename="harness evaluate --format table" />
					</div>
				</ScrollReveal>
			</section>

			{/* Act 3: See It In Action */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="See It In Action" color="green" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						Simulated gate evaluation run
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Click "Run Evaluation" to watch each gate execute and report its result,
						just like <code className="text-brand-cyan">harness evaluate</code> does.
					</p>
				</ScrollReveal>

				<ScrollReveal delay={0.1}>
					<div className="glass rounded-lg p-6">
						{/* Controls */}
						<div className="flex gap-3 mb-6">
							<button
								type="button"
								onClick={runEvaluation}
								disabled={running}
								className="px-4 py-2 rounded-lg text-sm font-medium bg-brand-green/20 text-brand-green border border-brand-green/30 hover:bg-brand-green/30 disabled:opacity-50 disabled:cursor-not-allowed transition-colors focus-visible:ring-2 focus-visible:ring-brand-cyan focus-visible:outline-none"
							>
								{running ? "Running..." : "Run Evaluation"}
							</button>
							{visibleCount > 0 && !running && (
								<button
									type="button"
									onClick={resetEvaluation}
									className="px-4 py-2 rounded-lg text-sm font-medium bg-surface-raised text-gray-400 border border-surface-border hover:text-gray-300 transition-colors focus-visible:ring-2 focus-visible:ring-brand-cyan focus-visible:outline-none"
								>
									Reset
								</button>
							)}
						</div>

						{/* Gate results */}
						<div className="space-y-2">
							{gates.map((gate, idx) => {
								const visible = idx < visibleCount;
								const isLatest = idx === visibleCount - 1 && running;
								return (
									<div
										key={gate.name}
										className={`flex items-center justify-between px-4 py-3 rounded-lg border transition-all duration-300 ${
											visible
												? gate.pass
													? "border-green-500/30 bg-green-500/5"
													: "border-red-500/30 bg-red-500/5"
												: "border-surface-border bg-surface-raised/30 opacity-30"
										} ${isLatest ? "ring-1 ring-brand-cyan" : ""}`}
									>
										<div className="flex items-center gap-3">
											<span className="text-lg" aria-hidden="true">
												{visible ? (gate.pass ? "\u2705" : "\u274C") : "\u23F3"}
											</span>
											<span
												className={`text-sm font-medium ${visible ? "text-white" : "text-gray-600"}`}
											>
												{gate.name}
											</span>
										</div>
										{visible && (
											<span
												className={`text-xs font-mono ${gate.pass ? "text-green-400" : "text-red-400"}`}
											>
												{gate.detail}
											</span>
										)}
									</div>
								);
							})}
						</div>

						{/* Summary */}
						{visibleCount >= gates.length && !running && (
							<div className="mt-6 pt-4 border-t border-surface-border text-center">
								<p className="text-brand-green font-semibold">
									8/8 gates passed — ready to merge
								</p>
							</div>
						)}

						{/* Progress bar */}
						{(running || visibleCount > 0) && (
							<div className="mt-4">
								<div className="h-1 bg-surface-raised rounded-full overflow-hidden">
									<div
										className="h-full bg-brand-green rounded-full transition-all duration-300"
										style={{ width: `${(visibleCount / gates.length) * 100}%` }}
									/>
								</div>
								<p className="text-xs text-gray-500 mt-1 text-right">
									{visibleCount}/{gates.length} gates
								</p>
							</div>
						)}
					</div>
				</ScrollReveal>
			</section>
		</DeepDiveLayout>
	);
}
