import { useState } from "react";
import CodeBlock from "../components/CodeBlock";
import DeepDiveLayout from "../components/DeepDiveLayout";
import FeatureItem from "../components/FeatureItem";
import GlowBadge from "../components/GlowBadge";
import ScrollReveal from "../components/ScrollReveal";
import { features } from "../data/features";

const observabilityFeatures = features.filter((f) => f.category === "observability");

const printfDebugging = `# What production debugging looks like without structured logging:

print("got here")
print(f"user is {user}")
print("about to call payment API")
console.log("response:", resp)
print(f"ERROR!!! {e}")
logger.info("something happened")
print(f"DEBUG: order_id={oid} total={t}")

# 6 months later:
# - No timestamps → can't correlate with incidents
# - No trace IDs → can't follow a request across services
# - No levels → can't filter noise from signal
# - No structure → can't query, aggregate, or alert
# - Mixed formats → grep is your only tool`;

const structuredConfig = `# Generated by: harness create → observability analyzer

# logging_config.py
LOGGING = {
    "version": 1,
    "formatters": {
        "structured": {
            "()": "harness.logging.StructuredFormatter",
            "fields": ["timestamp", "level", "domain", "trace_id", "message"]
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "structured"
        }
    },
    "root": {"level": "INFO", "handlers": ["console"]}
}`;

const observeOutput = `$ harness observe --domain auth --level warn,error --tail

{"ts":"2024-12-15T14:23:01Z","level":"WARN","domain":"auth","trace":"a1b2c3","msg":"Rate limit approaching: 4/5 attempts for user_id=u_892"}
{"ts":"2024-12-15T14:23:03Z","level":"ERROR","domain":"auth","trace":"a1b2c3","msg":"Login failed: invalid credentials for user_id=u_892"}
{"ts":"2024-12-15T14:23:18Z","level":"WARN","domain":"auth","trace":"d4e5f6","msg":"OAuth token refresh failed, retrying: provider=github"}
{"ts":"2024-12-15T14:23:22Z","level":"ERROR","domain":"auth","trace":"d4e5f6","msg":"OAuth callback timeout: provider=github, elapsed=5.2s"}`;

type LogLevel = "INFO" | "WARN" | "ERROR";
type Domain = "auth" | "billing" | "notifications";

interface LogEntry {
	timestamp: string;
	level: LogLevel;
	domain: Domain;
	traceId: string;
	message: string;
}

const logEntries: LogEntry[] = [
	{
		timestamp: "14:23:01.234",
		level: "INFO",
		domain: "auth",
		traceId: "a1b2c3d4",
		message: "Login attempt started for user_id=u_892",
	},
	{
		timestamp: "14:23:01.412",
		level: "INFO",
		domain: "auth",
		traceId: "a1b2c3d4",
		message: "Credential validation passed",
	},
	{
		timestamp: "14:23:01.567",
		level: "INFO",
		domain: "auth",
		traceId: "a1b2c3d4",
		message: "Session created: ttl=86400s",
	},
	{
		timestamp: "14:23:02.100",
		level: "INFO",
		domain: "billing",
		traceId: "e5f6a7b8",
		message: "Invoice generated: invoice_id=inv_2847 amount=$149.00",
	},
	{
		timestamp: "14:23:02.340",
		level: "WARN",
		domain: "billing",
		traceId: "e5f6a7b8",
		message: "Payment retry scheduled: attempt 2/3 for inv_2847",
	},
	{
		timestamp: "14:23:03.001",
		level: "ERROR",
		domain: "billing",
		traceId: "e5f6a7b8",
		message: "Payment failed: gateway_timeout for inv_2847",
	},
	{
		timestamp: "14:23:03.210",
		level: "INFO",
		domain: "notifications",
		traceId: "c9d0e1f2",
		message: "Email queued: template=welcome recipient=user@example.com",
	},
	{
		timestamp: "14:23:03.890",
		level: "WARN",
		domain: "notifications",
		traceId: "c9d0e1f2",
		message: "Email delivery delayed: smtp_queue_depth=147",
	},
	{
		timestamp: "14:23:04.100",
		level: "INFO",
		domain: "auth",
		traceId: "f3a4b5c6",
		message: "OAuth callback received: provider=github",
	},
	{
		timestamp: "14:23:04.560",
		level: "ERROR",
		domain: "auth",
		traceId: "f3a4b5c6",
		message: "OAuth token exchange failed: invalid_grant",
	},
	{
		timestamp: "14:23:05.001",
		level: "INFO",
		domain: "billing",
		traceId: "d7e8f9a0",
		message: "Subscription renewed: plan=pro user_id=u_441",
	},
	{
		timestamp: "14:23:05.234",
		level: "WARN",
		domain: "auth",
		traceId: "b1c2d3e4",
		message: "Rate limit approaching: 4/5 attempts for ip=203.0.113.42",
	},
	{
		timestamp: "14:23:05.890",
		level: "INFO",
		domain: "notifications",
		traceId: "a5b6c7d8",
		message: "Push notification sent: device_id=d_9923 topic=order_update",
	},
	{
		timestamp: "14:23:06.120",
		level: "ERROR",
		domain: "notifications",
		traceId: "a5b6c7d8",
		message: "Push delivery failed: device_token_expired for d_9923",
	},
	{
		timestamp: "14:23:06.450",
		level: "INFO",
		domain: "billing",
		traceId: "e9f0a1b2",
		message: "Refund processed: amount=$29.00 reason=duplicate_charge",
	},
];

const levelColors: Record<LogLevel, string> = {
	INFO: "text-green-400",
	WARN: "text-yellow-400",
	ERROR: "text-red-400",
};

const domainColors: Record<Domain, string> = {
	auth: "text-brand-purple",
	billing: "text-brand-cyan",
	notifications: "text-brand-green",
};

export default function ObservabilityPage() {
	const [levelFilter, setLevelFilter] = useState<Set<LogLevel>>(new Set(["INFO", "WARN", "ERROR"]));
	const [domainFilter, setDomainFilter] = useState<Set<Domain>>(
		new Set(["auth", "billing", "notifications"]),
	);

	const toggleLevel = (level: LogLevel) => {
		setLevelFilter((prev) => {
			const next = new Set(prev);
			if (next.has(level)) {
				if (next.size > 1) next.delete(level);
			} else {
				next.add(level);
			}
			return next;
		});
	};

	const toggleDomain = (domain: Domain) => {
		setDomainFilter((prev) => {
			const next = new Set(prev);
			if (next.has(domain)) {
				if (next.size > 1) next.delete(domain);
			} else {
				next.add(domain);
			}
			return next;
		});
	};

	const filteredLogs = logEntries.filter(
		(entry) => levelFilter.has(entry.level) && domainFilter.has(entry.domain),
	);

	return (
		<DeepDiveLayout categoryId="observability">
			{/* Act 1: The Problem */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Problem" color="purple" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						printf debugging in production
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Without structured logging, production debugging means grepping through inconsistent
						print statements with no timestamps, no trace IDs, and no way to correlate events across
						services.
					</p>
				</ScrollReveal>
				<ScrollReveal delay={0.2}>
					<CodeBlock code={printfDebugging} lang="python" filename="your-codebase.py" />
				</ScrollReveal>
			</section>

			{/* Act 2: The Solution */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Solution" color="cyan" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						17 observability features from structured logs to effectiveness scoring
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Harness generates structured logging config, log format linters, environment isolation,
						health checks, browser automation, and telemetry hooks — everything needed to make your
						application legible to both humans and agents.
					</p>
				</ScrollReveal>

				<div className="grid gap-3 mb-8">
					{observabilityFeatures.map((f) => (
						<div key={f.id} id={f.id}>
							<FeatureItem feature={f} />
						</div>
					))}
				</div>

				<ScrollReveal delay={0.1}>
					<div className="space-y-6">
						<CodeBlock
							code={structuredConfig}
							lang="python"
							filename="logging_config.py (generated)"
						/>
						<CodeBlock code={observeOutput} lang="json" filename="harness observe --domain auth" />
					</div>
				</ScrollReveal>
			</section>

			{/* Act 3: See It In Action */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="See It In Action" color="green" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						Interactive structured log stream
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Filter by log level and domain to see how structured logging makes it easy to find
						exactly the signal you need in production.
					</p>
				</ScrollReveal>

				<ScrollReveal delay={0.1}>
					<div className="glass rounded-lg p-6">
						{/* Filters */}
						<div className="flex flex-wrap gap-6 mb-6">
							{/* Level filters */}
							<div>
								<span className="text-xs text-gray-500 uppercase tracking-wide mb-2 block">
									Level
								</span>
								<div className="flex gap-2">
									{(["INFO", "WARN", "ERROR"] as LogLevel[]).map((level) => (
										<button
											key={level}
											type="button"
											role="switch"
											aria-checked={levelFilter.has(level)}
											onClick={() => toggleLevel(level)}
											className={`px-3 py-1.5 rounded text-xs font-mono border transition-colors focus-visible:ring-2 focus-visible:ring-brand-cyan focus-visible:outline-none ${
												levelFilter.has(level)
													? `${levelColors[level]} border-current bg-current/10`
													: "text-gray-600 border-surface-border hover:text-gray-400"
											}`}
										>
											{level}
										</button>
									))}
								</div>
							</div>

							{/* Domain filters */}
							<div>
								<span className="text-xs text-gray-500 uppercase tracking-wide mb-2 block">
									Domain
								</span>
								<div className="flex gap-2">
									{(["auth", "billing", "notifications"] as Domain[]).map((domain) => (
										<button
											key={domain}
											type="button"
											role="switch"
											aria-checked={domainFilter.has(domain)}
											onClick={() => toggleDomain(domain)}
											className={`px-3 py-1.5 rounded text-xs font-mono border transition-colors focus-visible:ring-2 focus-visible:ring-brand-cyan focus-visible:outline-none ${
												domainFilter.has(domain)
													? `${domainColors[domain]} border-current bg-current/10`
													: "text-gray-600 border-surface-border hover:text-gray-400"
											}`}
										>
											{domain}
										</button>
									))}
								</div>
							</div>
						</div>

						{/* Log count */}
						<div className="text-xs text-gray-500 mb-3">
							Showing {filteredLogs.length} of {logEntries.length} entries
						</div>

						{/* Log stream */}
						<div className="bg-surface rounded-lg border border-surface-border overflow-hidden">
							<div className="overflow-x-auto max-h-96 overflow-y-auto">
								<div className="p-3 space-y-0.5 font-mono text-xs">
									{filteredLogs.map((entry) => (
										<div
											key={`${entry.timestamp}-${entry.traceId}-${entry.message}`}
											className="flex gap-2 py-0.5 hover:bg-white/5 rounded px-1"
										>
											<span className="text-gray-600 shrink-0">{entry.timestamp}</span>
											<span className={`shrink-0 w-12 ${levelColors[entry.level]}`}>
												{entry.level.padEnd(5)}
											</span>
											<span className={`shrink-0 w-28 ${domainColors[entry.domain]}`}>
												{entry.domain}
											</span>
											<span className="text-gray-600 shrink-0">{entry.traceId}</span>
											<span className="text-gray-300">{entry.message}</span>
										</div>
									))}
									{filteredLogs.length === 0 && (
										<div className="text-gray-600 text-center py-8">
											No log entries match the current filters
										</div>
									)}
								</div>
							</div>
						</div>
					</div>
				</ScrollReveal>
			</section>
		</DeepDiveLayout>
	);
}
