import { useState } from "react";
import CodeBlock from "../components/CodeBlock";
import DeepDiveLayout from "../components/DeepDiveLayout";
import FeatureItem from "../components/FeatureItem";
import GlowBadge from "../components/GlowBadge";
import ScrollReveal from "../components/ScrollReveal";
import { features } from "../data/features";

const principlesFeatures = features.filter((f) => f.category === "principles");

const repeatedReviews = `PR #142 — reviewer: "Magic number on line 47, extract to constant"
PR #145 — reviewer: "Magic number on line 23, extract to constant"
PR #151 — reviewer: "Magic number on line 89, please use a named constant"
PR #153 — reviewer: "Hardcoded string on line 12, move to config"
PR #156 — reviewer: "Hardcoded string on line 34, this should be configurable"
PR #159 — reviewer: "Missing error context on line 67, wrap with domain error"
PR #161 — reviewer: "Magic number again... can we automate this?"
PR #164 — reviewer: "Same hardcoded URL as last sprint, still not in config"

# 8 PRs, same 3 comments, every single time.
# Humans shouldn't be linting for patterns machines can catch.`;

const principlesMd = `# PRINCIPLES.md (generated by harness)

## P003 — Structured Error Handling
All errors must be wrapped in domain-specific error types with context.
- Bad:  \`raise Exception("failed")\`
- Good: \`raise AuthError("login failed", user_id=uid, provider="oauth")\`
Severity: critical | Auto-fixable: no

## P011 — No Magic Numbers
Numeric literals (except 0, 1, -1) must be named constants.
- Bad:  \`if retries > 3:\`
- Good: \`if retries > MAX_RETRY_COUNT:\`
Severity: warning | Auto-fixable: yes (extract to module-level constant)

## P018 — No Hardcoded Strings
User-facing strings and URLs must come from config or i18n.
- Bad:  \`url = "https://api.example.com/v2"\`
- Good: \`url = settings.API_BASE_URL\`
Severity: warning | Auto-fixable: partial`;

const violationReport = `$ harness lint --check principles

  P011  src/billing/calculator.py:47
  │ if amount > 10000:
  │ ─── magic number 10000, extract to named constant
  │
  P018  src/auth/service.py:12
  │ redirect_url = "https://login.example.com/callback"
  │ ─── hardcoded URL, move to settings/config
  │
  P003  src/notifications/sender.py:89
  │ except Exception as e:
  │ ─── bare exception, wrap in NotificationError with context

  3 violations (1 critical, 2 warnings) in 0.8s`;

interface Scanner {
	id: string;
	label: string;
	principle: string;
	enabled: boolean;
}

const sampleCode = `def process_order(order_id: str, items: list) -> dict:
    """Process an order and calculate totals."""
    subtotal = sum(item["price"] * item["qty"] for item in items)

    if subtotal > 10000:                          # line 5
        discount = subtotal * 0.15
    elif subtotal > 5000:                         # line 7
        discount = subtotal * 0.10
    else:
        discount = 0

    tax = (subtotal - discount) * 0.08            # line 12
    total = subtotal - discount + tax

    if total > 50000:                             # line 15
        notify_url = "https://alerts.example.com/high-value"
        send_alert(notify_url, order_id, total)

    try:                                          # line 19
        result = charge_payment(order_id, total)
    except Exception as e:
        log(f"Payment failed: {e}")
        raise

    return {"order_id": order_id, "total": total, "status": "charged"}`;

interface Violation {
	line: number;
	scanner: string;
	message: string;
}

const violations: Violation[] = [
	{ line: 5, scanner: "P011", message: "magic number 10000 → ORDER_DISCOUNT_TIER_2" },
	{ line: 6, scanner: "P011", message: "magic number 0.15 → TIER_2_DISCOUNT_RATE" },
	{ line: 7, scanner: "P011", message: "magic number 5000 → ORDER_DISCOUNT_TIER_1" },
	{ line: 8, scanner: "P011", message: "magic number 0.10 → TIER_1_DISCOUNT_RATE" },
	{ line: 12, scanner: "P011", message: "magic number 0.08 → TAX_RATE" },
	{ line: 15, scanner: "P011", message: "magic number 50000 → HIGH_VALUE_THRESHOLD" },
	{ line: 16, scanner: "P018", message: "hardcoded URL → settings.ALERT_WEBHOOK_URL" },
	{ line: 21, scanner: "P003", message: "bare except Exception → PaymentError with context" },
	{ line: 22, scanner: "P003", message: "unstructured log → structured log with trace_id" },
];

export default function PrinciplesPage() {
	const [scanners, setScanners] = useState<Scanner[]>([
		{ id: "P011", label: "No Magic Numbers", principle: "P011", enabled: false },
		{ id: "P018", label: "No Hardcoded Strings", principle: "P018", enabled: false },
		{ id: "P003", label: "Structured Errors", principle: "P003", enabled: false },
	]);

	const toggleScanner = (id: string) => {
		setScanners((prev) => prev.map((s) => (s.id === id ? { ...s, enabled: !s.enabled } : s)));
	};

	const enabledScannerIds = new Set(scanners.filter((s) => s.enabled).map((s) => s.id));
	const activeViolations = violations.filter((v) => enabledScannerIds.has(v.scanner));

	const codeLines = sampleCode.split("\n");

	const violationsByLine = new Map<number, Violation[]>();
	for (const v of activeViolations) {
		const existing = violationsByLine.get(v.line) ?? [];
		existing.push(v);
		violationsByLine.set(v.line, existing);
	}

	return (
		<DeepDiveLayout categoryId="principles">
			{/* Act 1: The Problem */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Problem" color="purple" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						Same code review comments, every PR
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Human reviewers spend their time catching the same mechanical issues sprint after sprint
						— magic numbers, hardcoded strings, bare exceptions. These are patterns machines should
						enforce, not people.
					</p>
				</ScrollReveal>
				<ScrollReveal delay={0.2}>
					<CodeBlock code={repeatedReviews} lang="bash" filename="code-review-history.log" />
				</ScrollReveal>
			</section>

			{/* Act 2: The Solution */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="The Solution" color="cyan" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						13 principles extracted, documented, and mechanically enforced
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Harness scans your codebase for recurring patterns, extracts them as golden principles
						with frequency data, and generates lint rules that catch violations before code review
						even begins.
					</p>
				</ScrollReveal>

				<div className="grid gap-3 mb-8">
					{principlesFeatures.map((f) => (
						<div key={f.id} id={f.id}>
							<FeatureItem feature={f} />
						</div>
					))}
				</div>

				<ScrollReveal delay={0.1}>
					<div className="space-y-6">
						<CodeBlock code={principlesMd} lang="yaml" filename="PRINCIPLES.md (generated)" />
						<CodeBlock
							code={violationReport}
							lang="bash"
							filename="harness lint --check principles"
						/>
					</div>
				</ScrollReveal>
			</section>

			{/* Act 3: See It In Action */}
			<section className="mb-20">
				<ScrollReveal>
					<GlowBadge text="See It In Action" color="green" />
					<h2 className="text-2xl font-bold text-white mt-4 mb-3">
						Toggle scanners to see violations in real code
					</h2>
					<p className="text-gray-400 mb-8 max-w-2xl">
						Enable each principle scanner below to highlight violations in the sample code. This is
						what harness catches automatically before your code reaches review.
					</p>
				</ScrollReveal>

				<ScrollReveal delay={0.1}>
					{/* Scanner toggles */}
					<div className="flex flex-wrap gap-3 mb-6">
						{scanners.map((s) => (
							<button
								key={s.id}
								type="button"
								role="switch"
								aria-checked={s.enabled}
								onClick={() => toggleScanner(s.id)}
								onKeyDown={(e) => {
									if (e.key === "Enter" || e.key === " ") {
										e.preventDefault();
										toggleScanner(s.id);
									}
								}}
								className={`px-4 py-2 rounded-lg text-sm font-medium border transition-all focus-visible:ring-2 focus-visible:ring-brand-cyan focus-visible:outline-none ${
									s.enabled
										? "border-brand-cyan bg-brand-cyan/15 text-brand-cyan"
										: "border-surface-border bg-surface-raised text-gray-500 hover:text-gray-300 hover:bg-white/5"
								}`}
							>
								<span className="font-mono text-xs mr-2">{s.id}</span>
								{s.label}
								<span className="ml-2">{s.enabled ? "ON" : "OFF"}</span>
							</button>
						))}
					</div>

					{/* Violation count */}
					<div className="text-sm text-gray-400 mb-4">
						{activeViolations.length > 0 ? (
							<span className="text-yellow-400">
								{activeViolations.length} violation{activeViolations.length !== 1 ? "s" : ""} found
							</span>
						) : (
							<span>Enable scanners above to detect violations</span>
						)}
					</div>

					{/* Code with inline violations */}
					<div className="glass rounded-lg overflow-hidden">
						<div className="flex items-center gap-2 px-4 py-2 border-b border-surface-border bg-surface-raised/50">
							<span className="text-xs font-mono text-gray-500">billing/calculator.py</span>
						</div>
						<div className="overflow-x-auto">
							<pre className="p-4 text-sm font-mono leading-relaxed">
								{codeLines.map((line, idx) => {
									const lineNum = idx + 1;
									const lineViolations = violationsByLine.get(lineNum);
									const hasViolation = lineViolations && lineViolations.length > 0;
									return (
										<div key={lineNum}>
											<div
												className={`flex ${hasViolation ? "bg-red-500/10 border-l-2 border-red-500" : ""}`}
											>
												<span className="w-10 shrink-0 text-right pr-3 text-gray-600 select-none">
													{lineNum}
												</span>
												<span className={hasViolation ? "text-red-300" : "text-gray-300"}>
													{line || "\u00A0"}
												</span>
											</div>
											{lineViolations?.map((v) => (
												<div
													key={`${v.line}-${v.scanner}-${v.message}`}
													className="flex pl-10 text-xs"
												>
													<span className="text-yellow-500 font-mono">
														{"  "}
														{v.scanner}: {v.message}
													</span>
												</div>
											))}
										</div>
									);
								})}
							</pre>
						</div>
					</div>
				</ScrollReveal>
			</section>
		</DeepDiveLayout>
	);
}
