#!/usr/bin/env bash
# -----------------------------------------------------------------------
# harness boot script — worktree: agent-harness-skills
# Generated by harness_skills.boot.generate_boot_script()
#
# Usage:  bash boot_agent-harness-skills.sh
#   Starts an isolated application instance on port 8601 and exits 0
#   once the health check at http://localhost:8601/health returns HTTP 2xx.
#   Exits 1 if the health check does not pass within 30s.
# -----------------------------------------------------------------------
set -euo pipefail

WORKTREE_ID="agent-harness-skills"
PORT="8601"
HEALTH_URL="http://localhost:8601/health"
HEALTH_TIMEOUT=30
HEALTH_INTERVAL=1.0
# working dir: inherited
# log file: inherited streams
# No extra environment variables.
# ── Isolation setup ──────────────────────────────────────────────────────
# No database isolation configured.
# ── Launch application ───────────────────────────────────────────────────
echo "[harness:boot] Starting instance for worktree=$WORKTREE_ID on port=$PORT"
python -m http.server $PORT &
APP_PID=$!
echo "[harness:boot] Process started with PID=$APP_PID"

# ── Wait for health check ─────────────────────────────────────────────────
START_TIME=$(date +%s)
while true; do
    NOW=$(date +%s)
    ELAPSED=$(( NOW - START_TIME ))
    if [ "$ELAPSED" -ge "$HEALTH_TIMEOUT" ]; then
        echo "[harness:boot] ERROR: health check timed out after ${ELAPSED}s" >&2
        kill "$APP_PID" 2>/dev/null || true
        exit 1
    fi
    HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
        -X GET \
        --max-time 5 \
        "$HEALTH_URL" 2>/dev/null || echo "000")
    if [[ "$HTTP_STATUS" =~ ^2 ]]; then
        echo "[harness:boot] Ready — health check passed (HTTP $HTTP_STATUS) in ${ELAPSED}s"
        exit 0
    fi
    echo "[harness:boot] Waiting for health check (HTTP $HTTP_STATUS, ${ELAPSED}s elapsed)…"
    sleep "$HEALTH_INTERVAL"
done
