#!/usr/bin/env python3
"""
scripts/check_module_boundaries.py
Module Boundary Violation Scanner

Enforces that all cross-package imports go through a package's declared public
surface (__init__.py / __all__).  Deep sub-module imports that bypass __init__
are reported as blocking violations and cause this script to exit non-zero,
failing the CI build.

Generated by /module-boundaries on 2026-03-23.
Re-run `/module-boundaries` to refresh domain definitions and this script.

Exit codes:
  0  — all boundary checks passed (no violations)
  1  — one or more boundary violations found
  2  — internal error (bad arguments, missing files, etc.)

Usage:
  # Scan entire project (default)
  python scripts/check_module_boundaries.py

  # Scan only specific package
  python scripts/check_module_boundaries.py --domain harness_skills.models

  # Emit JSON report
  python scripts/check_module_boundaries.py --format json

  # Write JSON report to file
  python scripts/check_module_boundaries.py --format json --output report.json

  # Dry-run (scan without printing per-file detail)
  python scripts/check_module_boundaries.py --summary-only
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# ── Domain registry ───────────────────────────────────────────────────────────
# Each Domain records:
#   principle_id  — MB* ID in .claude/principles.yaml
#   name          — human-readable label shown in reports
#   pkg_dotted    — dotted import prefix (e.g. "harness_skills.models")
#   src_dir       — project-relative directory; imports *within* here are ok
#
# A violation is any line outside `src_dir` that contains:
#   from <pkg_dotted>.<sub_module> import ...
# (i.e. the import descends at least one level below the package root)


@dataclass(frozen=True)
class Domain:
    principle_id: str
    name: str
    pkg_dotted: str   # e.g. "harness_skills.models"
    src_dir: str      # e.g. "harness_skills/models"


# ── Domains (generated by /module-boundaries 2026-03-23) ─────────────────────
DOMAINS: list[Domain] = [
    # harness_skills root — intentionally exports nothing; callers use sub-pkgs.
    # No deep-import check needed for the root itself (it has no submodule surface
    # that callers should be bypassing).  MB001 is a guard principle, not a pattern.
    # harness_skills/cli  (MB002)
    Domain("MB002", "harness_skills/cli",        "harness_skills.cli",        "harness_skills/cli"),
    # harness_skills/gates  (MB003)
    Domain("MB003", "harness_skills/gates",      "harness_skills.gates",      "harness_skills/gates"),
    # harness_skills/generators  (MB004)
    Domain("MB004", "harness_skills/generators", "harness_skills.generators", "harness_skills/generators"),
    # harness_skills/models  (MB005)
    Domain("MB005", "harness_skills/models",     "harness_skills.models",     "harness_skills/models"),
    # harness_skills/plugins  (MB006)
    Domain("MB006", "harness_skills/plugins",    "harness_skills.plugins",    "harness_skills/plugins"),
    # harness_skills/utils  (MB007)
    Domain("MB007", "harness_skills/utils",      "harness_skills.utils",      "harness_skills/utils"),
    # harness_dashboard  (MB008)
    Domain("MB008", "harness_dashboard",         "harness_dashboard",         "harness_dashboard"),
    # dom_snapshot_utility  (MB009)
    Domain("MB009", "dom_snapshot_utility",      "dom_snapshot_utility",      "dom_snapshot_utility"),
    # log_format_linter  (MB010)
    Domain("MB010", "log_format_linter",         "log_format_linter",         "log_format_linter"),
]

# ── Types ─────────────────────────────────────────────────────────────────────


@dataclass
class Violation:
    principle_id: str
    domain_name: str
    file_path: str
    line_number: int
    line_text: str
    import_path: str   # the full deep import path found
    is_private: bool   # True when the imported symbol starts with _


@dataclass
class ScanResult:
    domains_scanned: int = 0
    files_scanned: int = 0
    violations: list[Violation] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return len(self.violations) == 0

    def violations_by_domain(self) -> dict[str, list[Violation]]:
        result: dict[str, list[Violation]] = {}
        for v in self.violations:
            result.setdefault(v.domain_name, []).append(v)
        return result


# ── File discovery ────────────────────────────────────────────────────────────

# Directories to skip entirely
_SKIP_DIRS: set[str] = {".venv", "venv", "node_modules", "__pycache__", ".git", "dist", "build", "tests"}


def _iter_python_files(root: Path) -> list[Path]:
    """Yield all .py files under root, skipping virtualenv / build dirs."""
    collected: list[Path] = []
    for p in root.rglob("*.py"):
        # Skip files inside any blacklisted directory component
        if any(part in _SKIP_DIRS for part in p.parts):
            continue
        if p.is_file():
            collected.append(p)
    return collected


# ── Deep-import detection ─────────────────────────────────────────────────────

def _build_pattern(domain: Domain) -> re.Pattern[str]:
    """
    Build a regex that matches lines containing a deep import into this domain.

    Matches:
        from harness_skills.models.base import ...
        from harness_skills.models.gate_configs import CoverageGateConfig
    Does NOT match:
        from harness_skills.models import Status          ← correct public import
        from harness_skills.models import (               ← correct multi-line
    """
    escaped = re.escape(domain.pkg_dotted)
    # Require at least one more component after the package root (the sub-module)
    return re.compile(
        r"^\s*from\s+" + escaped + r"\.\w[\w.]*\s+import",
        re.MULTILINE,
    )


def _is_private_import(line: str) -> bool:
    """Return True if the line imports a leading-underscore (private) symbol."""
    # from foo.bar import _symbol  |  from foo.bar import x, _y, z
    return bool(re.search(r"\bimport\s+[^#\n]*\b_\w+", line))


def _extract_import_path(line: str) -> str:
    """Extract the `from X.Y.Z` portion from an import line."""
    m = re.match(r"\s*from\s+([\w.]+)\s+import", line)
    return m.group(1) if m else line.strip()


def scan_file(
    path: Path,
    domain: Domain,
    pattern: re.Pattern[str],
    root: Path,
) -> list[Violation]:
    """Scan one file for deep imports into domain; return list of Violation."""
    # Files inside the domain's own package directory are allowed to do internal imports
    try:
        rel = path.relative_to(root)
    except ValueError:
        rel = path
    rel_str = str(rel)

    # Normalise separator for cross-platform safety
    if rel_str.replace("\\", "/").startswith(domain.src_dir.replace("\\", "/")):
        return []  # intra-package import — allowed

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []

    violations: list[Violation] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if pattern.search(line):
            violations.append(
                Violation(
                    principle_id=domain.principle_id,
                    domain_name=domain.name,
                    file_path=rel_str,
                    line_number=lineno,
                    line_text=line.rstrip(),
                    import_path=_extract_import_path(line),
                    is_private=_is_private_import(line),
                )
            )
    return violations


# ── Main scanner ──────────────────────────────────────────────────────────────

def scan(
    root: Path,
    domains: list[Domain],
) -> ScanResult:
    result = ScanResult(domains_scanned=len(domains))
    py_files = _iter_python_files(root)
    result.files_scanned = len(py_files)

    for domain in domains:
        pattern = _build_pattern(domain)
        for py_file in py_files:
            result.violations.extend(scan_file(py_file, domain, pattern, root))

    return result


# ── Reporters ─────────────────────────────────────────────────────────────────

_SEP = "━" * 72


def report_human(result: ScanResult, summary_only: bool = False) -> None:
    print(_SEP)
    print("  Module Boundary Violation Scanner")
    print(_SEP)
    print(f"  Domains checked : {result.domains_scanned}")
    print(f"  Files scanned   : {result.files_scanned}")
    print(f"  Violations found: {len(result.violations)}")
    print()

    if result.passed:
        print("  All module boundary checks passed.")
        print(_SEP)
        return

    by_domain = result.violations_by_domain()

    print(f"  BLOCKING VIOLATIONS ({len(result.violations)} total)")
    print()

    for domain_name, viols in sorted(by_domain.items()):
        print(f"  [{viols[0].principle_id}] {domain_name}  ({len(viols)} violation(s))")
        if not summary_only:
            for v in viols:
                priv_tag = " [PRIVATE]" if v.is_private else ""
                print(f"    {v.file_path}:{v.line_number}{priv_tag}")
                print(f"      {v.line_text.strip()}")
            print()
        else:
            print()

    print()
    print("  Enforcement: import from the package root (__init__.py) only.")
    print("  See .claude/principles.yaml IDs MB001-MB015 for full rules.")
    print()
    print("  CI GATE FAILED — resolve boundary violations before merge.")
    print(_SEP)


def report_json(result: ScanResult) -> dict:
    by_domain = result.violations_by_domain()
    return {
        "passed": result.passed,
        "summary": {
            "domains_checked": result.domains_scanned,
            "files_scanned": result.files_scanned,
            "total_violations": len(result.violations),
            "domains_with_violations": len(by_domain),
            "private_symbol_violations": sum(
                1 for v in result.violations if v.is_private
            ),
        },
        "violations": [
            {
                "principle_id": v.principle_id,
                "domain": v.domain_name,
                "file": v.file_path,
                "line": v.line_number,
                "import_path": v.import_path,
                "is_private": v.is_private,
                "text": v.line_text.strip(),
            }
            for v in result.violations
        ],
    }


# ── CLI ────────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Module Boundary Violation Scanner — fails builds on deep imports",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Project root to scan (default: current directory)",
    )
    parser.add_argument(
        "--domain",
        default=None,
        help=(
            "Restrict scan to a single domain package (dotted name, "
            "e.g. harness_skills.models). Scans all domains if omitted."
        ),
    )
    parser.add_argument(
        "--format",
        choices=["human", "json"],
        default="human",
        help="Output format (default: human)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Write JSON report to this file path (only with --format json)",
    )
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Print per-domain counts only, not individual violation lines",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"ERROR: --root '{root}' is not a directory.", file=sys.stderr)
        return 2

    # Filter domains
    domains = DOMAINS
    if args.domain:
        domains = [d for d in DOMAINS if d.pkg_dotted == args.domain]
        if not domains:
            known = ", ".join(d.pkg_dotted for d in DOMAINS)
            print(
                f"ERROR: unknown domain '{args.domain}'.\nKnown domains: {known}",
                file=sys.stderr,
            )
            return 2

    # Scan
    try:
        result = scan(root, domains)
    except Exception as exc:
        print(f"ERROR during scan: {exc}", file=sys.stderr)
        return 2

    # Report
    if args.format == "json":
        payload = report_json(result)
        json_str = json.dumps(payload, indent=2)
        print(json_str)
        if args.output:
            Path(args.output).write_text(json_str, encoding="utf-8")
    else:
        report_human(result, summary_only=args.summary_only)
        if args.output:
            payload = report_json(result)
            Path(args.output).write_text(json.dumps(payload, indent=2), encoding="utf-8")

    return 0 if result.passed else 1


if __name__ == "__main__":
    sys.exit(main())
