#!/usr/bin/env python3
"""Standalone harness initialization script for non-Claude-Code environments.

Usage:
    python scripts/harness_init.py [--profile starter|standard|advanced] [--project-root .] [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def _detect_stack_simple(root: Path) -> dict:
    """Simple stack detection without importing harness_skills."""
    stack = {"primary_language": "unknown", "framework": "unknown"}

    indicator_map = {
        "pyproject.toml": ("Python", "unknown"),
        "setup.py": ("Python", "unknown"),
        "package.json": ("JavaScript/TypeScript", "unknown"),
        "Cargo.toml": ("Rust", "unknown"),
        "go.mod": ("Go", "unknown"),
        "pom.xml": ("Java", "unknown"),
        "Gemfile": ("Ruby", "unknown"),
    }

    for filename, (lang, framework) in indicator_map.items():
        if (root / filename).exists():
            stack["primary_language"] = lang
            stack["framework"] = framework
            break

    return stack


def _generate_config(profile: str, stack: dict) -> str:
    """Generate a minimal harness.config.yaml."""
    return f"""# harness.config.yaml — generated by harness_init.py
# Profile: {profile}
# Language: {stack['primary_language']}
# Generated: {datetime.now(tz=timezone.utc).isoformat()}

active_profile: {profile}

profiles:
  {profile}:
    gates:
      regression:
        enabled: true
        fail_on_error: true
      coverage:
        enabled: true
        threshold: {'80' if profile == 'starter' else '90'}
      lint:
        enabled: true
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Initialize harness for a project")
    parser.add_argument("--profile", choices=["starter", "standard", "advanced"], default="starter")
    parser.add_argument("--project-root", default=".", help="Project root directory")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing files")
    args = parser.parse_args()

    root = Path(args.project_root).resolve()
    if not root.is_dir():
        print(f"ERROR: {root} is not a directory", file=sys.stderr)
        return 1

    stack = _detect_stack_simple(root)
    config = _generate_config(args.profile, stack)

    if args.dry_run:
        print("--- harness.config.yaml ---")
        print(config)
        print(f"\nDetected stack: {json.dumps(stack)}")
        print("(dry-run: no files written)")
        return 0

    config_path = root / "harness.config.yaml"
    config_path.write_text(config)
    print(f"Created: {config_path}")
    print(f"Profile: {args.profile}")
    print(f"Detected: {stack['primary_language']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
