#!/bin/sh
# =============================================================================
# harness-init.sh — POSIX shell harness initializer
#
# For teams NOT using the Claude Code IDE integration or Python.
# Detects project language from package files and creates a minimal
# harness.config.yaml with the starter profile.
#
# Usage:
#   sh harness-init.sh [--project-root <dir>] [--profile starter|standard|advanced]
#   sh harness-init.sh --help
# =============================================================================
set -e

# ── defaults ─────────────────────────────────────────────────────────────────
PROFILE="starter"
PROJECT_ROOT="."
SHOW_HELP=0

# ── argument parsing ─────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --project-root)
      PROJECT_ROOT="$2"
      shift 2
      ;;
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    -h|--help)
      SHOW_HELP=1
      shift
      ;;
    *)
      echo "Unknown flag: $1" >&2
      exit 1
      ;;
  esac
done

if [ "$SHOW_HELP" = 1 ]; then
  echo "Usage: sh harness-init.sh [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  --project-root <dir>   Project root directory (default: .)"
  echo "  --profile <name>       Profile: starter, standard, advanced (default: starter)"
  echo "  -h, --help             Show this help message"
  echo ""
  echo "Detects project language and creates harness.config.yaml."
  exit 0
fi

# ── validate project root ────────────────────────────────────────────────────
if [ ! -d "$PROJECT_ROOT" ]; then
  echo "ERROR: $PROJECT_ROOT is not a directory" >&2
  exit 1
fi

# ── detect language ──────────────────────────────────────────────────────────
DETECTED_LANG="unknown"

if [ -f "$PROJECT_ROOT/pyproject.toml" ] || [ -f "$PROJECT_ROOT/setup.py" ]; then
  DETECTED_LANG="Python"
elif [ -f "$PROJECT_ROOT/package.json" ]; then
  DETECTED_LANG="JavaScript/TypeScript"
elif [ -f "$PROJECT_ROOT/go.mod" ]; then
  DETECTED_LANG="Go"
elif [ -f "$PROJECT_ROOT/Cargo.toml" ]; then
  DETECTED_LANG="Rust"
fi

# ── resolve coverage threshold ───────────────────────────────────────────────
if [ "$PROFILE" = "starter" ]; then
  COVERAGE_THRESHOLD=80
else
  COVERAGE_THRESHOLD=90
fi

# ── generate harness.config.yaml ─────────────────────────────────────────────
CONFIG_PATH="$PROJECT_ROOT/harness.config.yaml"

cat > "$CONFIG_PATH" <<EOF
# harness.config.yaml — generated by harness-init.sh
# Profile: $PROFILE
# Language: $DETECTED_LANG

active_profile: $PROFILE

profiles:
  $PROFILE:
    gates:
      regression:
        enabled: true
        fail_on_error: true
      coverage:
        enabled: true
        threshold: $COVERAGE_THRESHOLD
      lint:
        enabled: true
EOF

# ── print summary ────────────────────────────────────────────────────────────
echo "Created: $CONFIG_PATH"
echo "Profile: $PROFILE"
echo "Detected: $DETECTED_LANG"
