#!/usr/bin/env bash
# =============================================================================
# worktree-create.sh — WorktreeCreate hook
#
# Called by Claude Code's EnterWorktree tool (or manually) when a new worktree
# is set up. Writes an .env.worktree file into the worktree and, optionally,
# starts isolated Docker Compose services.
#
# Environment variables provided by Claude Code:
#   WORKTREE_PATH   — absolute path to the new worktree
#   WORKTREE_NAME   — slug name of the worktree (branch / random id)
#
# Fallback: if not set, derived from the current directory.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

WORKTREE_PATH="${WORKTREE_PATH:-$PWD}"
WORKTREE_NAME="${WORKTREE_NAME:-$(basename "$WORKTREE_PATH")}"

echo "==> [worktree-create] Setting up isolation for worktree: ${WORKTREE_NAME}"
echo "    Path: ${WORKTREE_PATH}"

# ── 1. Derive isolated environment ───────────────────────────────────────────
# shellcheck source=scripts/worktree-env.sh
source "${SCRIPT_DIR}/worktree-env.sh" "${WORKTREE_NAME}"

# ── 2. Create data directory ──────────────────────────────────────────────────
DATA_DIR="${WORKTREE_PATH}/.worktree-data"
mkdir -p "${DATA_DIR}"

# ── 3. Write .env.worktree into the worktree ──────────────────────────────────
ENV_FILE="${WORKTREE_PATH}/.env.worktree"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by scripts/worktree-create.sh — DO NOT COMMIT
# Worktree: ${WORKTREE_NAME}  |  Slot: ${WORKTREE_SLOT}
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

WORKTREE_NAME=${WORKTREE_NAME}
WORKTREE_SLOT=${WORKTREE_SLOT}

# ── Service ports ─────────────────────────────────────────────────────────────
GRAFANA_PORT=${GRAFANA_PORT}
LOKI_PORT=${LOKI_PORT}
VECTOR_PORT=${VECTOR_PORT}
STATE_PORT=${STATE_PORT}

# ── Database (SQLite — separate file per worktree) ────────────────────────────
STATE_DB_URL=sqlite+aiosqlite:///${DATA_DIR}/claw_forge_${WORKTREE_NAME}.db

# ── Docker Compose (isolates containers by project name) ─────────────────────
COMPOSE_PROJECT_NAME=claw_forge_wt_${WORKTREE_NAME}

# ── Inherit base credentials from parent .env (do not duplicate secrets here)
# Load with: set -a; source .env; source .env.worktree; set +a
EOF

echo "    Wrote: ${ENV_FILE}"

# ── 4. Start isolated observability stack (optional) ─────────────────────────
# Set WORKTREE_START_SERVICES=1 to auto-start Docker services on worktree creation.
if [[ "${WORKTREE_START_SERVICES:-0}" == "1" ]]; then
  OBS_COMPOSE="${PROJECT_ROOT}/observability/docker-compose.worktree.yml"
  if [[ -f "${OBS_COMPOSE}" ]]; then
    echo "    Starting isolated observability services (slot=${WORKTREE_SLOT})..."
    set -a
    # Load base secrets, then override with worktree ports
    [[ -f "${PROJECT_ROOT}/.env" ]] && source "${PROJECT_ROOT}/.env"
    source "${ENV_FILE}"
    set +a
    docker compose \
      --project-name "${COMPOSE_PROJECT_NAME}" \
      -f "${OBS_COMPOSE}" \
      up -d --quiet-pull
    echo "    Grafana  : http://localhost:${GRAFANA_PORT}  (admin/admin)"
    echo "    Loki API : http://localhost:${LOKI_PORT}"
    echo "    Vector   : http://localhost:${VECTOR_PORT}"
  else
    echo "    [skip] ${OBS_COMPOSE} not found — skipping Docker services"
  fi
fi

# ── 5. Register slot in central registry ─────────────────────────────────────
REGISTRY="${PROJECT_ROOT}/.worktree-registry"
# Append entry (idempotent — remove old entry for same name first)
grep -v "^${WORKTREE_NAME}=" "${REGISTRY}" 2>/dev/null > "${REGISTRY}.tmp" || true
echo "${WORKTREE_NAME}=${WORKTREE_SLOT}" >> "${REGISTRY}.tmp"
mv "${REGISTRY}.tmp" "${REGISTRY}"

echo "==> [worktree-create] Done. Load env with:"
echo "    set -a; source .env; source .env.worktree; set +a"
