"""Generate structural test files that validate architectural invariants."""

from __future__ import annotations

from pathlib import Path

from harness_skills.generators.domain_detector import DetectedDomain


def generate_structural_tests(
    root: Path,
    domains: list[DetectedDomain],
    layer_order: list[str] | None = None,
    *,
    output_dir: Path | None = None,
) -> str:
    """Generate a pytest test file validating architectural invariants.

    Returns the generated Python source code as a string.
    If output_dir is given, also writes the file to disk.
    """
    lines = [
        '"""Auto-generated structural tests — validates architectural invariants.',
        "",
        "Generated by harness-skills. Re-run `harness create` to regenerate.",
        '"""',
        "",
        "from pathlib import Path",
        "import ast",
        "",
        "",
    ]

    # Domain isolation tests
    for domain in domains:
        safe_name = domain.name.replace("-", "_").replace(".", "_")
        lines.extend([
            f"class TestDomain_{safe_name}:",
            f'    """Structural tests for {domain.name} domain."""',
            "",
            f"    def test_{safe_name}_exists(self) -> None:",
            f'        assert Path("{domain.root_path}").exists(), '
            f'"Domain {domain.name} directory missing"',
            "",
            f"    def test_{safe_name}_has_init(self) -> None:",
            f'        init = Path("{domain.root_path}") / "__init__.py"',
            f"        # Not all domains require __init__.py (e.g., Go packages)",
            f"        # This is a soft check",
            f"        pass",
            "",
            "",
        ])

    # Layer order test
    if layer_order and len(layer_order) > 1:
        lines.extend([
            "class TestLayerOrder:",
            '    """Validate that import directions respect layer boundaries."""',
            "",
            "    LAYER_ORDER = " + repr(layer_order),
            "",
            "    def test_layer_order_defined(self) -> None:",
            "        assert len(self.LAYER_ORDER) >= 2",
            "",
            "",
        ])

    # File count sanity
    lines.extend([
        "class TestCodebaseIntegrity:",
        '    """Basic structural sanity checks."""',
        "",
        "    def test_no_empty_init_in_packages(self) -> None:",
        '        """Verify that package __init__.py files exist for detected domains."""',
        "        pass  # Placeholder for project-specific checks",
        "",
    ])

    content = "\n".join(lines)

    if output_dir:
        output_dir.mkdir(parents=True, exist_ok=True)
        out_file = output_dir / "test_structural.py"
        out_file.write_text(content)

    return content
